services:
  web:
    image: hwr44ever/codeigniter3-najam
    #build:
     # context: .
      #dockerfile: php.dockerfile
    container_name: php_cont
    ports:
      - 8080:80
    user: "1000:1000"
    volumes:
      - .:/var/www/html/
    depends_on:
      mysqldb:
        condition: service_healthy  
  mysqldb:
    image: mysql:5.7
    restart: always
    container_name: mysql_cont
    environment:
      - MYSQL_ROOT_PASSWORD=hwr
      - MYSQL_USER=waqas
      - MYSQL_PASSWORD=waqaspass
      - MYSQL_DATABASE=najamtraders_records
    command: --default-authentication-plugin=mysql_native_password

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql  

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    container_name: phpmyadmin_cont
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysqldb
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=hwr
    depends_on:
      - mysqldb
volumes:
  db_data: